#!/usr/bin/env node
/**
 * SYNC ROUTES — backend/src/api/**  →  frontend/src/app/api/**
 *
 * Next.js can only serve route handlers from frontend/src/app/api. This script
 * generates a one-line re-export shim for every handler in the backend so the
 * implementations stay in this package while Next.js keeps serving them.
 *
 * Run after changing any backend handler:  npm run sync
 */
import { readdirSync, statSync, writeFileSync, mkdirSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const BACKEND_API = join(__dirname, '..', 'src', 'api');
const FRONTEND_API = join(__dirname, '..', '..', 'frontend', 'src', 'app', 'api');

const HTTP_EXPORTS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS', 'dynamic', 'revalidate', 'runtime'];

const GENERATED_MARKER = '// GENERATED by backend/scripts/sync-routes.mjs — do not edit. Source: backend/src/api';

/** Recursively find every route.ts under dir. */
function findRoutes(dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...findRoutes(full));
    } else if (name === 'route.ts') {
      out.push(full);
    }
  }
  return out;
}

/** Extract which HTTP methods/constants a handler file actually exports. */
function findExports(filePath) {
  const src = readFileSync(filePath, 'utf8');
  const found = [];
  for (const name of HTTP_EXPORTS) {
    const re = new RegExp(`export\\s+(?:async\\s+)?(?:const|function)\\s+${name}\\b`);
    if (re.test(src)) found.push(name);
  }
  return found;
}

const shimTargets = [];

for (const handlerPath of findRoutes(BACKEND_API)) {
  const rel = relative(BACKEND_API, handlerPath);           // e.g. hr/employees/route.ts
  const target = join(FRONTEND_API, rel);                   // frontend/src/app/api/hr/employees/route.ts
  const importPath = `@backend/api/${rel.split(sep).join('/')}`.replace(/\/route\.ts$/, '/route');

  const names = findExports(handlerPath);
  if (names.length === 0) {
    console.warn(`  ! no exports found: ${rel}`);
    continue;
  }

  mkdirSync(dirname(target), { recursive: true });
  const body = `${GENERATED_MARKER}\nexport { ${names.join(', ')} } from '${importPath}';\n`;
  writeFileSync(target, body);
  shimTargets.push(rel);
  console.log(`  + ${rel}  (${names.join(', ')})`);
}

// Remove frontend route files that were previously synced/copied but no longer
// exist in the backend (only for the moved namespaces).
const MANAGED = ['hr', 'sales', 'manager', 'employee', 'client', 'auth', 'applications'];
for (const ns of MANAGED) {
  const feDir = join(FRONTEND_API, ns);
  if (!existsSync(feDir)) continue;
  for (const feRoute of findRoutes(feDir)) {
    const rel = relative(FRONTEND_API, feRoute);
    const beRoute = join(BACKEND_API, rel);
    if (!existsSync(beRoute)) {
      const src = readFileSync(feRoute, 'utf8');
      if (src.includes('GENERATED by backend/scripts/sync-routes.mjs') || src.startsWith('//')) {
        rmSync(feRoute);
        console.log(`  - removed stale shim: ${rel}`);
      } else {
        console.warn(`  ! frontend route not in backend (not auto-removed): ${rel}`);
      }
    }
  }
}

console.log(`\n✓ Synced ${shimTargets.length} route handlers into the frontend.`);
